Algoritmo "Exercício 4"
// Descrição   : Dada temperatura em Celsius algoritimo transforma esse valor para Fahrenheit.
// Autor(a)    : Leonardo Tsuneo Yamamoto
// Data atual  : 27/04/2019
Var
// Seção de Declarações das variáveis 
c, f, result: real

Inicio
// INPUT
escreva("Insira temperatura em Celsius: ")
leia(c)

// Cálculo
result <- (9 * c + 160) / 5

// OUTPUT
escreva("A temperatura de ",c,"°C equivale a ",result,"°F")

Fimalgoritmo